#ifndef _TEST_ARRAY_H_
#define _TEST_ARRAYH_
void testArray();
void testRemoveDuplicates();
void testRemoveDuplicatesII();
void testFindMedianSortedArrays();
void testLongestConsecutive();
void testGetPermutation();
void testTrap();
void testClimbStairs();
#endif //_TEST_ARRAY_H_